version: '3'

tasks:
  run:
    cmds:
      - echo 'Run API app localy'
      - go run backend/cmd/app/main.go
    silent: true
  up:
    cmds:
      - echo 'Up docker-compose envirentment'
      - docker compose -f env/docker-compose.yaml up -d
    silent: true
  dc:
    cmds:
      - docker compose -f env/docker-compose.yaml {{.CLI_ARGS}}
  down:
    cmds:
      - echo 'Down docker-compose envirentment'
      - docker compose -f env/docker-compose.yaml down
    silent: true
