FROM node:21

WORKDIR /app

COPY entrypoint.sh /usr/local/bin/

RUN chmod 777 /usr/local/bin/entrypoint.sh \
    && ln -s /usr/local/bin/entrypoint.sh /

EXPOSE 8080

ENV PORT=8080

ENTRYPOINT ["entrypoint.sh"]

CMD ["npm", "start"]
